// <auto-generated />
using System;
using ExpenseBot.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpenseBot.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExpenseBotDbContext))]
    partial class ExpenseBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpenseBot.Api.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("first_name");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("TelegramUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_telegram_user_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ExpenseBot.Api.Domain.Entities.Expense", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<int>("TelegramMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_message_id");

                    b.HasKey("Id")
                        .HasName("pk_expenses");

                    b.HasIndex("CategoryId", "LedgerId");

                    b.HasIndex("LedgerId", "CreatedByUserId");

                    b.HasIndex("LedgerId", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_expenses_ledger_occurred_at");

                    b.HasIndex("LedgerId", "TelegramMessageId")
                        .IsUnique()
                        .HasDatabaseName("ux_expenses_ledger_id_telegram_message_id");

                    b.HasIndex("LedgerId", "CategoryId", "OccurredAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_expenses_ledger_category_occurred_at");

                    b.ToTable("expenses", null, t =>
                        {
                            t.HasCheckConstraint("ck_expenses_amount", "amount > 0");

                            t.HasCheckConstraint("ck_expenses_currency", "currency ~ '^[A-Z]{3}$'");
                        });
                });

            modelBuilder.Entity("ExpenseBot.Api.Domain.Entities.ExpenseCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("emoji");

                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasAlternateKey("Id", "LedgerId")
                        .HasName("ak_categories_id_ledger_id");

                    b.HasIndex("LedgerId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_ledger_id_normalized_name");

                    b.HasIndex("LedgerId", "SortOrder", "Id")
                        .HasDatabaseName("ix_categories_ledger_sort_order");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("ExpenseBot.Api.Domain.Entities.ExpenseDraft", b =>
                {
                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.PrimitiveCollection<int[]>("FlowMessageIds")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("flow_message_ids");

                    b.Property<int?>("PromptMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_message_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("LedgerId", "UserId")
                        .HasName("pk_expense_drafts");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_expense_drafts_expires_at");

                    b.HasIndex("CategoryId", "LedgerId");

                    b.ToTable("expense_drafts", (string)null);
                });

            modelBuilder.Entity("ExpenseBot.Api.Domain.Entities.ExpenseLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("default_currency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.Property<string>("TelegramChatType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("telegram_chat_type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_expense_ledgers");

                    b.HasIndex("TelegramChatId")
                        .IsUnique()
                        .HasDatabaseName("ux_expense_ledgers_telegram_chat_id");

                    b.ToTable("expense_ledgers", null, t =>
                        {
                            t.HasCheckConstraint("ck_expense_ledgers_currency", "default_currency ~ '^[A-Z]{3}$'");
                        });
                });

            modelBuilder.Entity("ExpenseBot.Api.Domain.Entities.LedgerMember", b =>
                {
                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.HasKey("LedgerId", "UserId")
                        .HasName("pk_ledger_members");

                    b.HasIndex("UserId");

                    b.ToTable("ledger_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_ledger_members_role", "role IN ('owner', 'admin', 'member')");
                        });
                });

            modelBuilder.Entity("ExpenseBot.Api.Domain.Entities.ProcessedTelegramUpdate", b =>
                {
                    b.Property<int>("UpdateId")
                        .HasColumnType("integer")
                        .HasColumnName("update_id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.HasKey("UpdateId")
                        .HasName("pk_processed_telegram_updates");

                    b.HasIndex("CompletedAtUtc")
                        .HasDatabaseName("ix_processed_telegram_updates_completed_at");

                    b.ToTable("processed_telegram_updates", (string)null);
                });

            modelBuilder.Entity("ExpenseBot.Api.Domain.Entities.Expense", b =>
                {
                    b.HasOne("ExpenseBot.Api.Domain.Entities.ExpenseCategory", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId", "LedgerId")
                        .HasPrincipalKey("Id", "LedgerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_categories");

                    b.HasOne("ExpenseBot.Api.Domain.Entities.LedgerMember", "Member")
                        .WithMany("Expenses")
                        .HasForeignKey("LedgerId", "CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_members");

                    b.Navigation("Category");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ExpenseBot.Api.Domain.Entities.ExpenseCategory", b =>
                {
                    b.HasOne("ExpenseBot.Api.Domain.Entities.ExpenseLedger", "Ledger")
                        .WithMany("Categories")
                        .HasForeignKey("LedgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categories_ledgers");

                    b.Navigation("Ledger");
                });

            modelBuilder.Entity("ExpenseBot.Api.Domain.Entities.ExpenseDraft", b =>
                {
                    b.HasOne("ExpenseBot.Api.Domain.Entities.ExpenseCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId", "LedgerId")
                        .HasPrincipalKey("Id", "LedgerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_expense_drafts_categories");

                    b.HasOne("ExpenseBot.Api.Domain.Entities.LedgerMember", "Member")
                        .WithOne("Draft")
                        .HasForeignKey("ExpenseBot.Api.Domain.Entities.ExpenseDraft", "LedgerId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_drafts_members");

                    b.Navigation("Category");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ExpenseBot.Api.Domain.Entities.LedgerMember", b =>
                {
                    b.HasOne("ExpenseBot.Api.Domain.Entities.ExpenseLedger", "Ledger")
                        .WithMany("Members")
                        .HasForeignKey("LedgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_members_ledgers");

                    b.HasOne("ExpenseBot.Api.Domain.Entities.AppUser", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_members_users");

                    b.Navigation("Ledger");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseBot.Api.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("ExpenseBot.Api.Domain.Entities.ExpenseCategory", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("ExpenseBot.Api.Domain.Entities.ExpenseLedger", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("ExpenseBot.Api.Domain.Entities.LedgerMember", b =>
                {
                    b.Navigation("Draft");

                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
